name: Update Counter

on:
  repository_dispatch:
    types: [update_count]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DB
        uses: actions/checkout@v3
        with:
          repository: dajohli007/my-counter-db
          path: db

      - name: Update Count
        run: |
          cd db
          CARD=${{ github.event.client_payload.card }}
          PWD_HASH=$(echo -n "${{ github.event.client_payload.pwd }}" | sha256sum | cut -d' ' -f1)
          
          # 使用jq更新JSON文件
          jq --arg card "$CARD" \
             --arg hash "$PWD_HASH" \
             '.cards[$card].used += 1' data/counts.json > tmp.json
          
          mv tmp.json data/counts.json

      - name: Commit Changes
        run: |
          cd db
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/counts.json
          git commit -m "Update count for ${{ github.event.client_payload.card }}"
          git push
